### PR TITLE
Add new README and config example

### PR DESCRIPTION
**Pull request by NekoNe**
Any suggestions?

### CODE REVIEW

**Review by M0nsteR — COMMENTED** [review]
I'm not quite sure about the title. Maybe this: "a Golang HTTP interface to the Knowdy database"?

**Comment by NekoNe** [comment]
It is not a HTTP interface. It is Golang package-wrapper. But it is supplied with HTTP server example.

**Comment by M0nsteR** [comment]
Let's make it sound better then: "A Golang wrapper for Knowdy" ?

**Comment by NekoNe** [comment]
> A Golang wrapper for Knowdy

Ok. Pull Request is updated.

**Review by M0nsteR — APPROVED** [review]

**Pull request merged**
